include!(concat!(env!("OUT_DIR"), "/NSObject.rs"));
include!(concat!(env!("OUT_DIR"), "/MacTypes.rs"));
include!(concat!(env!("OUT_DIR"), "/acl.rs"));
include!(concat!(env!("OUT_DIR"), "/hfs_unistr.rs"));
include!(concat!(env!("OUT_DIR"), "/message.rs"));
include!(concat!(env!("OUT_DIR"), "/types.rs"));
pub mod MetalKit;
pub mod ModelIO;
pub mod CoreFoundation;
pub mod Metal;
pub mod IOSurface;
pub mod QuartzCore;
pub mod OpenGL;
pub mod CoreVideo;
pub mod CoreGraphics;
pub mod AppKit;
pub mod CoreData;
pub mod CoreServices;
pub mod DiskArbitration;
pub mod Security;
pub mod CoreImage;
pub mod ImageIO;
pub mod Foundation;
